### ISSUE TITLE
it does't work to bind a pid to node

### ISSUE THREAD

**Issue by colin-zhou** [cloudsigma/cgroupspy#12]
it seems that this library didn't support bind a process to some created node.
I did something like following, it turns out had none effect and node.controller.procs kept empty.
node.controller.procs.append(2341)

**Comment by prim** [comment]
You need to execute `node.controller.procs = [2341]` to trigger saving of the procs file.

**Comment by cs-cruz** [comment]
The problem was clarified in the previous message

**Comment by cs-cruz** [comment]
The problem was clarified in the previous message:
