### ISSUE TITLE
push 0.1.3 to pypi

### ISSUE THREAD

**Issue by joemiller** [cloudsigma/cgroupspy#6]
It looks like only 0.1.2 is available via pip but 0.1.3 is latest version in GH.

**Comment by jonlocs** [comment]
Hi @joemiller .

Now it's possible download from pypi versions 0.1.3 and 0.1.4

https://pypi.python.org/pypi/cgroupspy/0.1.3
https://pypi.python.org/pypi/cgroupspy/0.1.4

Best regards

**Comment by jjlopez** [comment]
Hi @joemiller .

Now it's possible download from pypi versions 0.1.3 and 0.1.4

https://pypi.python.org/pypi/cgroupspy/0.1.3
https://pypi.python.org/pypi/cgroupspy/0.1.4

Best regards
